services:

  excalidraw-store:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8402:8080"

    environment:
      - PORT=8080
      - DATA_DIR=/data
    volumes:
      - ./excalidraw-storage:/data
